### ISSUE TITLE
Mod Incompatibility: Lil'Wings vs. Fabricae Ex Nihilo

### ISSUE THREAD

**Issue by Jurklein** [TropheusJ/milk-lib#5]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 22/08/2022 17:29
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'lilwings'!
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
at net.minecraft.class_310.(class_310.java:452)
at net.minecraft.client.main.Main.main(Main.java:197)
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.IllegalStateException: An incompatible provider was already registered for item milk_bucket. Provider: wraith.fabricaeexnihilo.modules.fluids.MilkFluid$$Lambda$9104/0x000000080225e490@7edde4fb.
at net.fabricmc.fabric.impl.transfer.fluid.CombinedProvidersImpl.getOrCreateItemEvent(CombinedProvidersImpl.java:97)
at net.fabricmc.fabric.api.transfer.v1.fluid.FluidStorage.combinedItemApiProvider(FluidStorage.java:105)
at io.github.tropheusj.milk.Milk.enableMilkFluid(Milk.java:112)
at com.toadstoolstudios.lilwings.FabricLilWings.onInitialize(FabricLilWings.java:28)
at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
... 7 more

**Comment by Jurklein** [comment]
Quoting here the original issue: https://github.com/terrarium-earth/Lil-Wings/issues/9

**Comment by TropheusJ** [comment]
can't be fixed on my side, reported to FabricaeExNihilo
